# fly.toml app configuration file generated for system32-crimson-hill-6347 on 2026-02-20T10:21:38Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'system32-crimson-hill-6347'
primary_region = 'fra'

[env]
  PORT = "3000" # add this where PORT matches the internal_port below

[processes]
  app = "node app.js" # add this

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
